en_text = """
Ice hockey is a team sport enjoyed by a wide variety of people around the world. The object of the sport is to move a hard rubber disk called a "puck" into the other team's net with a hockey stick. Two teams with six players on each team engage in this fast-paced sport on a hard and slippery ice rink. Players may reach a speed of 30 kilometers per hour sending the puck into the air. At this pace, both the players and the puck can be a cause of serious danger.
The speed of the sport and the slippery surface of the ice rink make it easy for players to fall down or bump into each other resulting in a variety of injuries. In an attempt to protect players, equipment such as helmets, gloves, and pads for the shoulders, elbows, and legs, has been introduced over the years. Despite these efforts, ice hockey has a high rate of concussions.
A concussion is an injury to the brain that affects the way it functions; it is caused by either direct or indirect impact to the head, face, neck, or elsewhere and can sometimes cause temporary loss of consciousness. In less serious cases, for a short time, players may be unable to walk straight or see clearly, or they may experience ringing in the ears. Some believe they just have a slight headache and do not realize they have injured their brains.
In addition to not realizing the seriousness of the injury, players tend to worry about what their coach will think. In the past, coaches preferred tough players who played in spite of the pain. In other words, while it would seem logical for an injured player to stop playing after getting hurt, many did not. Recently, however, it has been found that concussions can have serious effects that last a lifetime. People with a history of concussion may have trouble concentrating or sleeping. Moreover, they may suffer from psychological problems such as depression and mood changes. In some cases, players may develop smell and taste disorders.
The National Hockey League (NHL), consisting of teams in Canada and the United States, has been making stricter rules and guidelines to deal with concussions. For example, in 2001, the NHL introduced the wearing of visors—pieces of clear plastic attached to the helmet that protect the face. At first, it was optional and many players chose not to wear them. Since 2013, however, it has been required. In addition, in 2004, the NHL began to give more severe penalties, such as suspensions and fines, to players who hit another player in the head deliberately.
The NHL also introduced a concussion spotters system in 2015. In this system, NHL officials with access to live streaming and video replay watch for visible indications of concussion during each game. At first, two concussion spotters, who had no medical training, monitored the game in the arena. The following year, one to four concussion spotters with medical training were added. They monitored each game from the League's head office in New York. If a spotter thinks that a player has suffered a concussion, the player is removed from the game and is taken to a "quiet room" for an examination by a medical doctor. The player is not allowed to return to the game until the doctor gives permission.
The NHL has made much progress in making ice hockey a safer sport. As more is learned about the causes and effects of concussions, the NHL will surely take further measures to ensure player safety. Better safety might lead to an increase in the number of ice hockey players and fans.
"""

ja_text = """
アイスホッケーは世界中でさまざまな人に楽しまれているチームスポーツだ。このスポーツの目的は，「パック」と呼ばれる硬いゴム製の円盤をホッケースティックで相手チームのネットに入れることだ。各チームに6人の選手がいる2つのチームが，硬くて滑りやすいアイスリンクでこのペースの速いスポーツをする。選手がパックを空中に打つ時，時速30キロに達することもある。この速度では，選手もパックも重大な危険の原因になる可能性があるのだ。
そのスポーツのスピードとアイスリンク表面の滑りやすさは，選手の転倒や，選手同士の衝突を容易に引き起こし，結果としていろいろなケガにつながる。長年にわたり，選手を守ろうとする試みにおいて，ヘルメット，グローブ，肩やひじや脚のパッドのような装備品が導入されてきている。しかしこのような努力にもかかわらず，アイスホッケーが脳しんとうにつながる確率は高い。
脳しんとうは，脳の機能に影響を与える脳の負傷だ。それは頭，顔，首などの部位への直接的または間接的な衝撃によって起こり，ときには一時的な意識喪失を起こすこともある。あまり深刻でない場合でも，短い時間，選手はまっすぐ歩けなかったり，はっきりと見えなくなったり，耳鳴りを経験することもある。選手の中には軽い頭痛だと思って，自分が脳を負傷していることに気づかない人もいる。
負傷の深刻さに気づかないことに加え，選手はコーチがどう思うかを心配する傾向にある。昔は，コーチは痛みにもかかわらずプレーするタフな選手をより好んだ。言い換えると，負傷した選手は負傷直後にプレーをやめるのが論理的であると思われるのに，多くはそうしなかったのだ。しかし最近，脳しんとうはその人の一生涯にわたって深刻な影響をおよぼす可能性があるとわかってきた。脳しんとうの病歴のある人は，集中力や睡眠に問題を抱えるかもしれないのだ。さらに，彼らはうつ病や情緒不安定のような精神的問題に苦しむかもしれないのだ。いくつかのケースでは，選手は嗅覚と味覚に障害を発症するかもしれないのだ。
カナダとアメリカのチームで構成されるナショナル・ホッケー・リーグ（NHL）は，脳しんとうに対処するためにより厳しいルールとガイドラインを作ってきた。たとえば，2001年，NHLはバイザー――つまりヘルメットに取りつけられた顔を保護する透明なプラスチック片を着用することを導入した。最初，それは任意で，多くの選手は着用しないことを選んだ。しかし2013年から，それは義務化された。加えて，2004年，NHLは故意に他の選手の頭部を殴打した選手に対し，出場停止や罰金などのより厳しいペナルティーを与え始めた。
2015年，NHLは脳しんとうスポッター（監視員）システムも導入した。このシステムは，ライブ配信やリプレイ映像にアクセスするNHLの公式スタッフが試合中に脳しんとうの見た目にわかる兆候を監視するのだ。最初は，医学的訓練を受けていない2人の脳しんとうスポッターがアリーナで試合を監視していた。その翌年，医療研修を受けた1〜4人の脳しんとうスポッターが追加された。彼らはニューヨークのリーグ本部オフィスから各試合を監視した。もしスポッターが，ある選手が脳しんとうを起こしているとみなすと，その選手は試合から外され，「安静室」に連れて行かれて医者の検査を受ける。医者が許可を出すまで，その選手は試合に戻ることを許されないのだ。
アイスホッケーをより安全なスポーツにすることにおいて，NHLは大きな進歩を成し遂げてきた。脳しんとうの原因や影響がより明らかになるにつれて，選手の安全を確実にするためにNHLがさらに対策を講じることは確かであろう。より高い安全性はアイスホッケー選手とファンの増加につながるであろう。
"""
